{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $svc.roleArn | quote }}
  labels:
    app: {{ $name }}
    {{- include "vpb-mma.labels" $ | nindent 4 }}
---
{{- end }}
